key: val
data_preprocessing:
  train_split: 0.8
  val_split: 0.15
  test_split: 0.15

AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # As vgg16 was trained on 224x224 images
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHT: imagenet
LEARNING_RATE: 0.01