artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/dataset/orgi
  source_URL: 'https://drive.google.com/file/d/1r158U4DLjXVDEHMMuwAymmGtXtbi_x4g/view?usp=drive_link'
  local_data_file: artifacts/dataset/orgi/breast_cancer_classification.zip
  unzip_dir: artifacts/dataset/orgi

data_preprocessing:
  root_dir: artifacts/dataset/orgi
  base_path: artifacts/dataset/idc
  train_split: 0.8
  val_split: 0.1
  training_dir: artifacts/dataset/idc/training
  testing_dir: artifacts/dataset/idc/testing
  validation_dir: artifacts/dataset/idc/validation


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  updated_model_path: artifacts/training/updated_model.h5
  training_data: artifacts/dataset/idc/training
  validation_data: artifacts/dataset/idc/validation
  test_data: artifacts/dataset/idc/testing
  params_epochs: 1
  params_batch_size: 32
  params_is_augmentation: true
  params_image_size: [224, 224]
  params_learning_rate: 0.001
  params_include_top: false
  params_classes: 2



  